modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="ragnorok_tale_of_the_vikings"
version="1.0.0"
displayName="Ragnorok: Tale of the Vikings"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kevin, MCreator"

[[dependencies.ragnorok_tale_of_the_vikings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




